version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api